# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Topogram
email: hi@topogram.io
subtitle: "Visualize how networks change over time and space."
tagline: Social network analysis for Humans
description: Topogram is an open-source software to visualize changes in networks over time and space. It relies on web technologies to provide a web experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://topogram.io" # the base hostname & protocol for your site
twitter_username: topoviz
github_username:  topogram
contact_email:  contact@topogram.io

# Build settings
markdown: kramdown

# collections
collections:
    events:
        output: true

future: true
